apiVersion: v1
kind: Service
metadata:
  name: p-fb-service
  namespace: production
  labels:
    app: p-fb
    env: production
spec:
  type: NodePort
  selector:
    app: p-fb
  ports:
    - port: 80
      protocol: TCP

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: p-fb-configmap
  namespace: production
  labels:
    app: p-fb
    env: production
data:
  config.php: |
    <?php
    $db_host = getenv("DB_HOST");
    $db_user = getenv("DB_USER");
    $db_pass = getenv("DB_PASS");
    $db_name = "dbsosmed";
    try {
    //create PDO connection
    $db = new PDO("mysql:host=$db_host;dbname=$db_name", $db_user, $db_pass);
    } catch(PDOException $e) {
    //show error
    die("Terjadi masalah: " . $e->getMessage());
    }

---

apiVersion: v1
kind: Secret
metadata:
  name: p-fb-secret
  namespace: production
  labels:
    app: p-fb
    env: production
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASS: UDd0U3lIcUo=
