apiVersion: apps/v1
kind: Deployment
metadata:
  name: p-wp-deployment
  namespace: production
  labels:
    app: p-wp
    env: production
spec:
  selector:
    matchLabels:
      app: p-wp
  replicas: 2
  template:
    metadata:
      labels:
        app: p-wp
    spec:
      volumes:
        - configMap:
            name: p-wp-configmap
          name: config-wp
      containers:
        - name: p-wp-pod
          image: $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:${BUILD_NUMBER}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-wp
              mountPath:  "/var/www/html/wp-config.php"
              subPath: "wp-config.php"
          env:  
            - name: DB_HOST    
              value: "database-1.chghgvrwjatk.ap-southeast-1.rds.amazonaws.com"
            - name: DB_USER    
              valueFrom:       
                secretKeyRef:
                  name: p-wp-secret
                  key: DB_USER  
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: p-wp-secret
                  key: DB_PASS
